# Site settings
title: Gavin Blog
SEOTitle: 甘泉的博客 | Gavin's Blog
header-img: img/home-bg-desk.jpg
email: ganquan3640@gmail.com
description: "Yesterday's the past, tomorrow's the future, but today is a gift."
keyword: "Gavin, Gavin Blog, 甘泉的博客, ganquan, 甘泉, Android, javascript, 逆向,应用安全"
url: "http://CarryGanLove.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/CarryGanLove/CarryGanLove.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Yesterday's the past, tomorrow's the future, but today is a gift!"
sidebar-avatar: /img/avatar.png     # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
github_username:    CarryGanLove
# facebook_username:  Quad Gan
jianshu_username:   f85192130fc7
#twitter_username:   CarryGanLove




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://CarryGanLove.com/）
# disqus_username: CarryGanLove

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: 76eaa50e7a1def63b6de                            #生成的clientID
  clientSecret: e6ac2d2eaa4940ccd35e25f888c6c32d4c3b5b10    #生成的clientSecret
  repo: CarryGanLove.github.io    #仓库名称
  owner: CarryGanLove    #github用户名
  admin: CarryGanLove
  distractionFreeMode: true #是否启用类似FB的阴影遮罩




# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: cb4585908d3d4413bbbd520ac9091d81

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: CarryGanLove.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "简书·Gavin",
        href: "https://www.jianshu.com/u/f85192130fc7"
    },{
        title: "MDN",
        href: "https://developer.mozilla.org/zh-CN/"
    },{
        title: "Android Developer",
        href: "https://developer.android.com"
    }
]
